### ISSUE TITLE
Traduction incomplète dans ch02

### ISSUE THREAD

**Issue by tristancaron** [dartlangfr/dart-up-and-running#27]
Bonjour,

Dans la première note, il est écrit :
```markdown
**Note:**
Vous pouvez avec la plupart des fonctionnalités en utilisant DartPad, tel que décris dans Up and running.
```

À la place de ce qui pourrait être :
```markdown
**Note:**
Vous pouvez essayer la plupart des fonctionnalités présentées dans Up and running en utilisant DartPad.
```

Originale :
`You can play with most of these features using DartPad, as described in Up and running.`

**Comment by VincentBostoen** [comment]
Merci de votre retour, on a corrigé en utilisant votre proposition de traduction.
N'hésitez pas si vous constatez d'autres coquilles.
